name: Context examples

on: ['push']

jobs:
  my-context:
    runs-on: ubuntu-latest
    steps:
    - name: My step context
      run: echo "Hello, my action $MY_ACTION and job $JOB"
      env:
        MY_ACTION: ${{ github.action}}
        JOB: ${{ job.id }}
